### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by LIMEKDEV** [JadeMin/aterbot#1]
itried it and followed all your steps and it didn't work. i might have done something wrong. could you make a youtube video on this?

**Comment by JadeMin** [comment]
https://github.com/LIMEKDEV/aternos-afkbot/blob/main/config.json#L2
https://github.com/LIMEKDEV/aternos-afkbot/blob/main/config.json#L3
Remove the dots at the end of the host and port in your repository ``config.json`` file.
![image](https://user-images.githubusercontent.com/36400787/180225225-40f97c43-a861-40f8-9d14-2ae7ffa472ab.png)


Also i'll upload a tutorial video for this later. thanks for the issue <3
