### ISSUE TITLE
Run isn't configured.

### ISSUE THREAD

**Issue by JustinsKittens** [JadeMin/aterbot#16]
`Run isn't configured. Try adding a .replit and configuring it https://docs.replit.com/programming-ide/configuring-run-button`

**Comment by JadeMin** [comment]
Maybe the `.replit` file not imported. I recommend to start over with the step 1.

**Comment by JustinsKittens** [comment]
Well, I thought that was the case, so I copied the code from the `.replit` file on Github into the `.replit` file on Replit, and it still didn't work

**Comment by JadeMin** [comment]
sorry but do that again, there was a mistake the configs.
