### ISSUE TITLE
gives new type of error

### ISSUE THREAD

**Issue by ElCunq** [JadeMin/aterbot#22]
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:478:5)
    at __node_internal_errnoException (node:internal/errors:608:12)
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
AFKBot got an error: Error: read ECONNRESET
Trying to reconnect in 5 seconds...

Bot gives this error and I couldn't solve it either. It just keeps joinning and leaving.

**Comment by JadeMin** [comment]
Can't reproduce. Maybe your aternos server or wrong config issue?

**Comment by JadeMin** [comment]
Not sure, but renaming your Aternos server url may helpful.

**Comment by JadeMin** [comment]
In additional, `ECONNRESET` means the other side of the TCP conversation closed the connection.
Your server might have disconnected your bot for some reason.
