### ISSUE TITLE
Getting an error 

### ISSUE THREAD

**Issue by Hmunjal2859** [JadeMin/aterbot#23]
{
	"client": {
		"host": "THEBOI555.aternos.me:58320",
		"port": "58230",
		"username": "AFK_BOT1234"
	},
	
	"! DO NOT EDIT BELOW !": "ONLY IF YOU KNOW WHAT YOU ARE DOING",
	"logLevel": ["error", "log", "debug"],
	"action": {
		"commands": ["forward", "back", "left", "right", "jump"],
		"holdDuration": 5000,
		"retryDelay": 15000
	}
}
Error: getaddrinfo ENOTFOUND THEBOI555.aternos.me:58320
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at __node_internal_ (node:internal/errors:712:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'THEBOI555.aternos.me:58320'
}

**Comment by JadeMin** [comment]
Remove `:58320` from your `host`.

Thank you for your interest <3
