### ISSUE TITLE
Unverified Username

### ISSUE THREAD

**Issue by ElCunq** [JadeMin/aterbot#26]
After the 1.20.1 update I got ` {"translate":"multiplayer.disconnect.unverified_username"}` error. Even my server is cracked. I couldn't figure out how to fix it. Can you help about it? Bots name is "KaramelBey".

**Comment by JadeMin** [comment]
Did you restarted your Aternos server after changing to `Offline Mode`?

**Comment by ElCunq** [comment]
> Did you restarted your Aternos server after changing to `Offline Mode`?

Yes I did. I tried to make it online mode start and again offline mod but it won't work.

**Comment by ElCunq** [comment]
so I made it. Sorry for the unneccesarry bother. I did the server online mod not offline. I mixed up the choices. Thanks for your help.
